arch_root: /mnt

hostname: bon

country: Germany
locales:
  - en_US
  - de_DE

user:
  name: croissong
  group: croissong
  uid: 1000
  comment: Jan Möller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

extra_packages:
  - git
  - ripgrep

extra_aur_packages: []

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S albert bash chromium conky flameshot git goldendict mime termite tmux vim xmonad xorg"
  deps:
    - conky
    - stow
    - xclip
    - python-jedi
    - source-highlight
    - hasktags
    - ctags

# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present