---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  environment:
    USER_HOME: "{{ user.home }}"
    DOTFILES_DIR: "{{ dotfiles.directory }}"

  pre_tasks:
    - include_role:
        name: system
        tasks_from: timedate

  tasks:
    - import_role: {name: pkgs}
    - import_role: {name: system}
    - import_role: {name: desktop}
    - import_role: {name: laptop}
    - import_role: {name: dotfiles}
    - import_role: {name: lang}
