---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  pre_tasks:
    - include_role:
        name: system
        tasks_from: timedate

    - name: set priv_dir
      tags: ['always']
      set_fact: priv_dir="{{ lookup('env','MY_PRIV') }}"
      become_user: "{{ user.name }}"

  tasks:
    - import_role: {name: pkgs}
    - import_role: {name: system}
    - import_role: {name: xorg}
    - import_role: {name: desktop}
    - import_role: {name: laptop}
    - import_role: {name: dotfiles}
    - import_role: {name: dev}
    - import_role: {name: lang}
    - import_role: {name: apps}
    - import_role: {name: tools}

  post_tasks:
    - import_role:
        name: pkgs
        tasks_from: maintenance
