---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  tasks:
    - import_role: {name: system}
    - import_role: {name: laptop}
    - import_role: {name: user}
