---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes

  pre_tasks:

    - name: set priv_dir
      tags: ['always']
      set_fact: priv_dir="{{ lookup('env','MY_PRIV') }}"
      become_user: "{{ user.name }}"

  tasks:
    - import_role: {name: pkgs}
    - import_role: {name: system}
    - import_role: {name: laptop}
    - import_role: {name: user}

  post_tasks:

    - import_role:
        name: pkgs
        tasks_from: maintenance
