---
- name: theme and fonts
  tags: ['theme', 'fonts']
  block:

    - name: install fonts
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - ttf-hack
          - ttf-dejavu
          - ttf-ubraille
          # Fonts to use asian characters
          - ttf-freefont
          - ttf-arphic-uming
          - ttf-baekmuk
          - ttf-indic-otf
          # Emoji
          - noto-fonts
          - ttf-hannom  # Vietnamese
          # Math
          - font-mathematica


    # via https://www.reddit.com/r/archlinux/comments/5r5ep8/make_your_arch_fonts_beautiful_easily/
    - name: beautiful fonts
      block:
        - name: enable font presets
          file:
            src: '{{ item.src }}'
            dest: '{{ item.dest }}'
            state: link
          with_items:
            - { src: '/etc/fonts/conf.avail/70-no-bitmaps.conf', dest: '/etc/fonts/conf.d/70-no-bitmaps.conf' }
            - { src: '/etc/fonts/conf.avail/10-sub-pixel-rgb.conf', dest: '/etc/fonts/conf.d/10-sub-pixel-rgb.conf' }
            - { src: '/etc/fonts/conf.avail/11-lcdfilter-default.conf', dest: '/etc/fonts/conf.d/11-lcdfilter-default.conf' }

        - name: copy system fontconfig
          copy: src=etc/fonts/local.conf dest=/etc/fonts/local.conf
