---
- name: xorg config
  block:
    - name: install Xorg server and extensions
      pacman: name={{ x_packages }} state=present
      vars:
        x_packages:
          - xorg
          - xorg-xinit
          - xterm
          - xf86-input-libinput
          - xf86-video-intel
          - arandr
          - autorandr

    - name: configure input devices
      copy: src=xorg/30-input.conf dest=/etc/X11/xorg.conf.d/30-input.conf

    - name: identify video adapter vendor
      shell: "set -o pipefail && lspci | grep VGA"
      args:
        executable: /bin/bash
      register: graphics
      changed_when: False

    - name: configure video driver
      copy: src=xorg/30-video.conf dest=/etc/X11/xorg.conf.d/30-video.conf
      when: "'Intel' in graphics.stdout"

    - name: add user to video group
      user: name={{ user.name }} groups=video append=yes

    - name: add user to audio group
      user: name={{ user.name }} groups=audio append=yes

    - name: stow xorg dotfiles
      stow: package=xorg
