---
- name: xorg config
  block:

    - name: filter xorg group packages
      shell: pacman -Sqg xorg | grep -v xorg-xsetroot
      register: filtered_xorg_packages_output
      changed_when: False

    - name: install Xorg server and extensions
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages: "{{ tmp_list + filtered_xorg_packages_output.stdout_lines }}"
        tmp_list:
          - xorg-xinit
          - xf86-input-libinput
          - xf86-video-intel
          - arandr
          - autorandr
          - compton
          - hsetroot

    - name: configure input devices
      copy: src=xorg/etc/X11/xorg.conf.d/30-input.conf dest=/etc/X11/xorg.conf.d/30-input.conf

    - name: identify video adapter vendor
      shell: "set -o pipefail && lspci | grep VGA"
      args:
        executable: /bin/bash
      register: graphics
      changed_when: False

    - name: configure video driver
      copy: src=xorg/etc/X11/xorg.conf.d/30-video.conf dest=/etc/X11/xorg.conf.d/30-video.conf
      when: "'Intel' in graphics.stdout"

    - name: add user to video group
      user: name={{ user.name }} groups=video append=yes

    - name: add user to audio group
      user: name={{ user.name }} groups=audio append=yes

    - name: stow xorg dotfiles
      become_user: "{{ user.name }}"
      stow: package=xorg
