---
- name: setup exa
  tags: ['exa']
  block:
    - name: symlink exa configs
      import_role: name=dotfiles tasks_from=register_dotfiles_util
      tags: alias
      vars: {dotfiles: exa}
    - name: install exa
      import_role: name=pkgs tasks_from=util__install_packages
      vars: {packages: exa}
