---
- name: setup fd
  tags: ['fd']
  block:
    - name: symlink fd configs
      import_role: name=dotfiles tasks_from=register_dotfiles_util
      tags: alias
      vars: {dotfiles: fd}
    - name: install fd
      import_role: name=pkgs tasks_from=util__install_packages
      vars: {packages: fd}
