---
- name: setup tools
  tags: ['tools']
  block:

    - import_tasks: shell.yml
    - import_tasks: vpn.yml

    - name: install other tools pkgs
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - cyberark-summon
          - electrum
          - gopass
          - minetime
          - pandoc
          - pass
          - rdesktop
          - s3cmd
          - sshfs
          - vagrant
          - virt-manager
          
    - name: install TwoFactorAuth pkgs
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - oath-toolkit
          - zbar

    - name: stow gopass priv dotfiles
      become_user: "{{ user.name }}"
      stow: package="gopass" source_dir="{{ priv_dir }}"
