---
- name: setup tools
  tags: ['tools']
  block:

    - import_tasks: shell.yml
    - import_tasks: vpn.yml

    - name: install other tools pkgs
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - electrum
          - pandoc
          - pass
          - sshfs
          - rdesktop
          - vagrant
          - virt-manager
          - s3cmd
          
    - name: install TwoFactorAuth pkgs
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - oath-toolkit
          - zbar
