---
- name: setup tools
  tags: ['tools']
  become_user: "{{ user.name }}"
  block:

    - name: enable tmux user service
      service: name=tmux scope=user enabled=yes state=started

    - name: install helmfile
      tags: ['helmfile']
      block:

        - include_tasks: utils/get_github_release.yml
          vars:
            binary: helmfile
            repo: roboll/helmfile
            asset: helmfile_linux_amd64
            get_tag_cmd: "helmfile -v | sed -n -e 's/^.*v.* //p'"
