---
- name: setup shell and terminal
  tags: ['shell']
  become_user: "{{ user.name }}"
  block:

    - name: create shell dir
      file:
        path: $HOME/.my/.shell
        state: directory

    - name: symlink shell configs
      import_role: name=dotfiles tasks_from=register_dotfiles_util
      tags: alias
      vars: {dotfiles: shell}

    - import_tasks: alacritty.yml
    - import_tasks: dtrx.yml
    - import_tasks: exa.yml
    - import_tasks: fd.yml
    - import_tasks: glances.yml
    - import_tasks: ripgrep.yml
    - import_tasks: tmux.yml
    - import_tasks: zsh.yml

    - name: install other shell packages
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - antibody-bin
          - fzf
          - jq
          - jp
          - yq
          # https://wiki.archlinux.org/index.php/Dash
          - dashbinsh
