---
- name: setup zsh
  tags: zsh
  block:
    - name: symlink zsh configs
      import_role: name=dotfiles tasks_from=register_dotfiles_util
      vars: {dotfiles: zsh}
    - name: install zsh
      import_role: name=pkgs tasks_from=util__install_packages
      vars: {packages: zsh}
