---
- name: js
  tags: js
  block:

    - name: stow js dotfiles
      stow: package=yarn
      become_user: "{{ user.name }}"

    - name: install js dev tools
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - prettier
          - yarn
