arch_root: /mnt

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: croissong
  group: croissong
  home: "/home/croissong"
  uid: 1000
  comment: Jan Möller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

extra_packages:
  - git
  - ripgrep
  - firefox-beta-bin
  - thunderbird-bin

extra_aur_packages:
  - exa
  - dunst
  - fd
  - dtrx
  - mitogen
  - slack-desktop
  - mattermost-desktop-bin

dotfiles:
  repo: "https://github.com/Croissong/.dotfiles"
  directory: "{{ user.home }}/dotfiles"
  install_cmd: "stow -d {{ user.home }}/dotfiles -S git gpg pass ssh tmux i3 perl-anyevent-i3 systemd dunst yarn"
  deps:
    - stow
    - xclip
    
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present

packages:
  - coreutils
  - glances
  - linux-firmware
  - lsof
  - moreutils
  - rsync
  - sysstat
  - pciutils
  - flameshot
  - autorandr
  - jq
  - pkg_scripts
  - yq
  - gnome-keyring
