arch_root: /mnt

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: &username croissong
  group: *username
  uid: 1000
  comment: Jan Möller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

repos:
  emacs: 'git@github.com:Croissong/.emacs.d.git'
  dotfiles: 'git@github.com:Croissong/dotfiles.git'
        
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present
