arch_root: /mnt

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: &username croissong
  group: *username
  uid: 1000
  comment: Jan Möller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

dotfiles_vars:
  repo: "https://github.com/Croissong/.dotfiles"
  standalone_dotfiles:
    - env
    - git
    - gpg
    - pass
    - ssh
  deps:
    - stow
    - xclip
    
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present

core_packages:
  - git
  - lsof
  - moreutils
  - rsync
  - sysstat
     
extra_packages:
  - dtrx
  - flameshot
  - glances
  - gnome-keyring
  - ripgrep
  - rmlint
  - rofi
