arch_root: /mnt

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: &username croissong
  group: *username
  home: /home/croissong
  uid: 1000
  comment: Jan Möller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

dotfiles:
  repo: "https://github.com/Croissong/.dotfiles"
  directory: &dotfiles_dir "{{ user.home }}/dotfiles"
  priv_dir: "{{ user.home }}/dotfiles/.priv"
  standalone_dotfiles:
    - dunst
    - env
    - git
    - gpg
    - i3
    - pass
    - ssh
    - tmux
    - yarn
    - yay
  deps:
    - stow
    - xclip
    
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present
     
extra_packages:
  - ansible-lint
  - autorandr
  - dunst
  - evince
  - exa
  - fd
  - flameshot
  - git
  - glances
  - gnome-keyring
  - jq
  - libreoffice-fresh
  - perl-anyevent-i3
  - ripgrep

extra_aur_packages:
  - dtrx
  - firefox-beta-bin
  - mattermost-desktop-bin
  - mitogen
  - pkg_scripts
  - slack-desktop
  - yq
