---
- name: setup mail client
  tags: ['mail']
  block:
    - name: install mail packages
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - offlineimap
