---
- name: setup media apps
  tags: ['media']
  block:
    - name: install media packages
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - acestream-launcher
          - feh
          - mpv
          - obs-studio
