---
- name: install AUR package helper yay
  aur: name=yay use=makepkg skip_installed=true
  become: yes
  become_user: "{{ user.name }}"
  tags: aur

- name: install downgrade script for downgrading packages
  become: no
  aur:
    use: yay
    name: downgrade
  tags: aur
