---
- name: pacman
  tags: pacman
  block:
    - name: 'configure Pacman: enable color'
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#?Color$'
        line: Color

    - name: 'configure pacman: enable verbose package lists'
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#?VerbosePkgLists$'
        line: VerbosePkgLists

    - name: refresh pacman cache and upgrade the system
      pacman: update_cache=yes upgrade=yes

    - name: install pacman cache cleanup timer
      copy: src=paccache.timer dest=/etc/systemd/system/paccache.timer
      notify:
        - reload systemd config
        - enable paccache timer

    - import_tasks: aur.yml
