---
- name: system
  tags: ['system']
  block:
    - import_tasks: locales.yml
    - import_tasks: console.yml
    - import_tasks: pam.yml
    - import_tasks: net.yml
    - import_tasks: systemd.yml
    - import_tasks: nftables.yml
    - import_tasks: physlock.yml

    - name: copy configs
      tags: ['config', 'debug']
      template:
        src: '{{ item.src }}'
        dest: '/{{ item.path }}'
        owner: root
      with_filetree: '../templates'
      when: item.state == 'file'


    - name: enable earlyoom service
      tags: ['systemd']
      service: name=earlyoom enabled=yes state=started
