---
- name: system
  tags: ['system']
  block:
    - import_tasks: locales.yml
    - import_tasks: console.yml
    - import_tasks: pam.yml
    - import_tasks: net.yml
    - import_tasks: systemd.yml
    - import_tasks: nftables.yml
    - import_tasks: physlock.yml

    - name: copy configs
      tags: ['config', 'debug']
      template:
        src: '{{ item.src }}'
        dest: '/{{ item.path }}'
        owner: root
      with_filetree: '../templates'
      when: item.state == 'file'

    - name: enable services
      tags: ['systemd']
      service: name={{ item }} enabled=yes state=started
      with_items:
      - systemd-networkd
      - systemd-resolved
      - earlyoom
