---
- name: system
  tags: ['system']
  block:
    - import_tasks: locales.yml
    - import_tasks: console.yml
    - import_tasks: pam.yml
    - import_tasks: net.yml
    - import_tasks: systemd.yml
    - import_tasks: nftables.yml
