---
- name: configure networking
  tags: ['net']
  block:

    - name: configure iwd
      tags: ['iwd']
      block:
        - name: install iwd
          import_role: name=pkgs tasks_from=util__install_packages
          vars:
            packages:
              - iwd

        - name: stow iwd dotfiles profiles
          stow:
            package: iwd
            source_dir: "{{ dotfiles.priv_dir }}/network"
            target_dir: /var/lib/iwd/

        - name: enable iwd service
          service: name=iwd enabled=yes state=started

    - name: networkd
      tags: ['systemd', 'systemd-networkd']
      block:

        - name: enable networkd
          service: name=systemd-networkd enabled=yes state=started

        - name: copy networkd configs
          copy: src=net/networkd/ dest=/
          notify: restart systemd-networkd

    - name: resolved
      tags: ['systemd', 'systemd-resolved']
      block:

        - name: install systemd-resolvconf
          import_role: name=pkgs tasks_from=util__install_packages
          vars:
            packages:
              - systemd-resolvconf

        - name: symlink resolv.conf stub
          file:
            src: "/run/systemd/resolve/stub-resolv.conf"
            dest: "/etc/resolv.conf"
            state: link

        - name: enable systemd-resolved
          service: name=systemd-resolved enabled=yes state=started

        - name: copy resolved configs
          copy: src=net/resolved/ dest=/
          notify: restart systemd-resolved
