---
- name: configure networking
  tags: ['net']
  block:

    - name: configure iwd
      tags: ['iwd']
      block:
        - name: copy iwd main config
          copy: src=net/iwd/main.conf dest=/etc/iwd/main.conf

        - name: enable iwd service
          service: name=iwd enabled=yes state=started

        - name: copy iwd configs
          copy: src="{{ priv_dir }}/iwd/" dest=/var/lib/iwd/
          notify: restart iwd

    - name: resolved
      tags: ['systemd', 'systemd-resolved']
      block:

        - name: symlink resolv.conf stub
          file:
            src: "/run/systemd/resolve/stub-resolv.conf"
            dest: "/etc/resolv.conf"
            state: link
