---
- name: pam.d config
  block:
    - name: stow pam.d dotfiles
      include_role:
        name: dotfiles
        tasks_from: util__stow_force_override
      vars:
        package: pam.d
        target_dir: /
  tags:
    - pamd

  
