- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted

- name: restart iwd
  systemd:
    name: iwd
    state: restarted

- name: restart nftables
  systemd:
    name: nftables
    state: restarted
