initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - modconf
  - block
  - sd-encrypt
  - filesystems
  - fsck

base_packages:
  - coreutils
  - linux-firmware
  - lsof
  - moreutils
  - rsync
  - sysstat
  - pciutils
