---
- name: install TLP power management
  pacman: name={{ item }} state=present
  with_items:
      - tlp
      - acpid
      - ethtool
      - smartmontools

- name: mask systemd radio service
  systemd: name=systemd-rfkill.service masked=true

- name: mask systemd radio socket
  systemd: name=systemd-rfkill.socket masked=true

- name: Enable TLP service
  service: name=tlp.service enabled=yes state=restarted

- name: Enable TLP sleep service
  service: name=tlp-sleep.service enabled=yes state=restarted
