---
- name: mask systemd radio service
  systemd: name=systemd-rfkill.service masked=true

- name: mask systemd radio socket
  systemd: name=systemd-rfkill.socket masked=true

- name: Enable TLP service
  service: name=tlp.service enabled=yes

# TODO: https://wiki.archlinux.org/index.php/TLP
