---

- name: configure initramfs build hooks
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: HOOKS="{{ initramfs_hooks | join(' ') }}"

- name: rebuild initramfs
  command: mkinitcpio -p {{ item }}
  with_items:
    - linux-zen
    - linux-lts
  

- name: restrict access permissions to initramfs
  file:
    path: "/boot/{{ item }}"
    mode: 0600
  with_items:
    - initramfs-linux-zen.img
    - initramfs-linux-zen-fallback.img
    - initramfs-linux-lts.img
    - initramfs-linux-lts-fallback.img

- name: install bootctl bootloader
  command: "bootctl --path=/boot install"

- name: create boot loader.conf
  template:
    src: loader.conf.j2
    dest: /boot/loader/loader.conf

- name: get arch PARTUUID
  shell: blkid {{ drive.device }}1 | sed 's/.*PARTUUID="\(.*\)"/\1/'
  register: cmd_output

- set_fact:
    root_partuuid: "{{ cmd_output.stdout }}"

- name: create boot entry arch
  template:
    src: arch.conf.j2
    dest: /boot/loader/entries/arch.conf

- name: create boot entry arch-lts
  template:
    src: arch-lts.conf.j2
    dest: /boot/loader/entries/arch-lts.conf
