---
- name: configure aur
  tags: ['aur']
  become_user: "{{ user.name }}"
  block:

    - name: install AUR package helper yay
      aur:
        name: yay
        use: makepkg
        aur_only: False
        skip_installed: True
