---
- name: configure aur
  tags: ['aur']
  become_user: "{{ user.name }}"
  block:

    - name: stow yay dotfiles config
      stow: package=yay

    - name: install AUR package helper yay
      import_tasks: util__install_packages.yml
      vars:
        use: makepkg
        skip_installed: True
        packages:
          - yay

    - name: install downgrade script for downgrading packages
      import_tasks: util__install_packages.yml
      vars:
        packages:
          - downgrade
