---
- name: install packages helper utility
  vars:
    pkg_manager: yay
  tags: ['always']
  block:

    - include_tasks: normalize_packages.yml
      vars:
        packages: "{{ registered_packages }}"
        exclude: "{{ excluded_packages }}"

    - set_fact:
        registered_packages: "{{ normalized_packages }}"

    - name: install packages
      when: registered_packages | length > 0
      aur:
        name: "{{ registered_packages }}"
        use: "{{ pkg_manager }}"
        aur_only: False
        skip_installed: True
      become_user: "{{ user.name }}"
