# pacdiff
---
- name: cleanup obsolete resources
  tags: ['maintenance', 'pkg_maintenace']
  block:

    - name: Clean orphan packages
      command: yay -Yc --noconfirm
      register: output
      changed_when: output.stdout.find('removing') != -1

    - name: Clean paccache.
      command: paccache -rk1
      register: output
      changed_when: output.stdout.find('packages removed') != -1
