---
- name: cleanup obsolete resources
  tags: ['pacman', 'maintenance']
  block:

    - name: Clean orphan packages
      command: yay -Yc

    - name: Clean paccache.
      command: paccache -rk1
      register: output
      changed_when: output.stdout.find('packages removed') != -1

    - name: cleanup unlisted packages
      tags: ['pkg_maintenace']
      block:
        - name: find explicitely installed packages
          command: pacman -qQet
          changed_when: False
          register: installed_packages_res

        - import_role: name=arch-bootstrap tasks_from=register_base_packages

        - name: add base packages registered package list
          set_fact:
            registered_packages: "{{ registered_packages + core_packages + base_packages.split() }}"

        - name: expand package groups
          command: "pacman -Sqg {{ registered_packages | join(' ')}}"
          changed_when: False
          failed_when: False
          register: expanded_groups_output

        - name: add expanded groups to registered package list
          set_fact:
            registered_packages: "{{ registered_packages + expanded_groups_output.stdout_lines }}"

        - debug: msg="{{ installed_packages_res.stdout_lines | difference(registered_packages) }}"
