---
- name: pkg repo mirrors
  tags: ['maintenance', 'mirrors']
  block:

    - include_tasks: utils/mirrorlist_checksum.yml

    - set_fact:
        mirrorlist_pre: "{{ mirrorlist_file }}"

    - name: update repository mirrors
      command: |
        reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist
      changed_when: false

    - include_tasks: utils/mirrorlist_checksum.yml

    - set_fact:
        mirrorlist_post: "{{ mirrorlist_file }}"

    - name: compare mirrorlist checksums
      debug: msg="mirrorlist changed"
      changed_when: True
      when: mirrorlist_pre.stat.checksum != mirrorlist_post.stat.checksum
