---
- name: configure pacman
  tags: ['pacman']
  block:

    - name: copy pacman configs
      copy: src=pacman/ dest=/

    - name: stow pacman user dotfiles
      become_user: "{{ user.name }}"
      stow: package=pacman

    - name: refresh pacman cache and upgrade the system
      pacman: update_cache=yes upgrade=yes
      tags: ['maintenance']

    - name: install pacman utils
      import_tasks: util__install_packages.yml
      vars:
        packages:
          - pkg_scripts
          - lzop # used in makepkg.conf
