---
- name: configure pacman
  tags: ['pacman']
  block:
    - name: stow pacman system dotfiles
      include_role:
        name: dotfiles
        tasks_from: util__stow_force_override
      vars:
        package: system
        source_dir: "{{ dotfiles.directory }}/pacman"
        target_dir: /

    - name: stow pacman user dotfiles
      stow:
        package: user
        source_dir: "{{ dotfiles.directory }}/pacman"

    - name: refresh pacman cache and upgrade the system
      pacman: update_cache=yes upgrade=yes
      tags: ['maintenance']
