---
- name: configure pacman
  tags: ['pacman']
  block:

    - name: copy pacman configs
      copy: src=pacman/ dest=/

    - name: copy pacman templates
      template: src=pacman/etc/pacman.d/hooks/pkglist.hook dest=/etc/pacman.d/hooks

    - name: refresh pacman cache and upgrade the system
      pacman: update_cache=yes upgrade=yes
      tags: ['maintenance']
