---
- name: register base packages
  tags: ['package', 'maintenace', 'pkg_maintenace']
  block:
    - include_tasks: normalize_packages.yml
      vars:
        packages:
          - base
          - linux-zen
          - linux-lts
          - base-devel
          - reflector
          - ansible
          - btrfs-progs
        unique:
          - which
          - util-linux
          - sed
          - gettext
          - grep
          - gawk
          - file
          - findutils
          - gzip
          - pacman
          - texinfo
        exclude:
          - linux
          - nano
          - netctl

    - name: register base packages
      set_fact:
        base_packages: "{{ normalized_packages }}"
      
