---
- name: install packages helper utility
  vars:
    pkg_manager: yay
    skip_installed: True
  block:

    - name: add package to registered packages list
      tags: ['maintenace', 'pkg_maintenace']
      vars:
         registered_packages: "{{custom_packages}}"
      block:
        - name: check duplicate packages
          fail: msg="duplicate package {{ item }}"
          when: item is defined
          loop: "{{registered_packages | intersect(packages)}}"

        - name: add packages to registered packages list
          set_fact:
            registered_packages: "{{ registered_packages + packages }}"


    - name: install packages
      tags: ['package']
      aur:
        name: "{{ packages }}"
        use: "{{ pkg_manager }}"
        aur_only: False
        skip_installed: True
      become_user: "{{ user.name }}"
