---
- name: install packages helper utility
  tags: ['always']
  vars:
    pkg_manager: yay
    skip_installed: False
    packages: []
  block:


    - name: install packages from aur
      aur:
        name: "{{ packages }}"
        use: "{{ pkg_manager }}"
        aur_only: False
        skip_installed: "{{ skip_installed }}"
      become_user: "{{ user.name }}"
      when: (packages | length) > 0
