---
- name: install packages helper utility
  tags: ['package']
  vars:
    pkg_manager: yay
    skip_installed: True
  block:

    - name: update installed package list
      tags: ['maintenace', 'pkg_maintenace']
      set_fact:
        registered_packages: "{{ registered_packages | default([]) + packages }}"
      failed_when: registered_packages | count !=  registered_packages | unique | count

    - name: install packages
      aur:
        name: "{{ packages }}"
        use: "{{ pkg_manager }}"
        aur_only: False
        skip_installed: True
      become_user: "{{ user.name }}"
