---
- name: install packages helper utility
  block:

    - name: add package to registered packages list
      tags: ['maintenace', 'pkg_maintenace']
      block:
        - name: check duplicate packages
          fail: msg="duplicate package {{ item }}"
          when: item is defined
          loop: "{{registered_packages | intersect(packages)}}"

        - name: add packages to registered packages list
          tags: ['package']
          set_fact:
            registered_packages: "{{ registered_packages + packages }}"
            excluded_packages: "{{ excluded_packages | default([]) + exclude | default([]) }}"
