---

- import_tasks: xorg.yml
- import_tasks: i3.yml
- import_tasks: emacs.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: networkd.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - feh 
    - redshift
    - dunst
    - rofi

- name: Register uid
  command: id -u {{ user.name }}
  register: uid

- block:
  - name: Delete redshift service display manager line
    # https://wiki.archlinux.org/index.php/redshift#Redshift_works_fine_when_invoked_as_a_command_but_fails_when_run_as_a_systemd_service
    lineinfile: dest=/usr/lib/systemd/user/redshift.service
                state=absent
                regexp='After=display-manager.service'

  - name: enable redshift service
    systemd:
      name: redshift.service
      enabled: True
      scope: user
      state: started
    become: True  
    become_user: "{{ user.name }}"
  tags:
    - redshift

- import_tasks: extra_packages.yml
