---

- import_tasks: xorg.yml
- import_tasks: i3.yml
- import_tasks: emacs.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - feh
    - redshift
    - dunst
    - rofi

- block:
  - name: stow redshift
    command: "stow -d ${HOME}/dotfiles -S redshift"
    become_user: "{{ user.name }}"

  - name: enable redshift service
    systemd:
      name: redshift.service
      enabled: True
      scope: user
      state: started
    become: True
    become_user: "{{ user.name }}"
  tags:
    - redshift
