---

- import_tasks: xorg.yml
- import_tasks: i3.yml
- import_tasks: emacs.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: networkd.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman: name={{ item }}
  with_items:
    - feh 
    - redshift
    - dunst
    - rofi

- name: Register uid
  command: id -u {{ user.name }}
  register: uid

- name: enable redshift service
  systemd:
    name: redshift.service
    enabled: True
    user: True
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}  
  become: True  
  become_user: "{{ user.name }}"

- import_tasks: extra_packages.yml
