---
- import_tasks: emacs.yml
- import_tasks: media.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman: name=cronie state=present
  notify:
    - enable cron
