---
- name: media configs
  tags: ['media']
  block:

    - name: install media codecs
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - flac
          - lame
          - opus
          - gstreamer
          - gst-libav
          - gstreamer-vaapi
          - gst-plugins-good
          - gst-plugins-ugly
          - gst-plugins-bad

    - name: install pulseaudio
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - alsa-tools
          - alsa-utils
          - pulseaudio
          - pulseaudio-alsa
          - pulseaudio-jack
          - pavucontrol
          - pamixer
          - paprefs

    - import_role: name=dotfiles tasks_from=register_dotfiles_util
      vars:
        dotfiles: pulseaudio
