---
- name: configure printing
  tags: ['printing']
  block:

    - name: add user to lp group
      user:
        name: "{{ user.name }}"
        groups: lp
        append: yes

    - name: enable CUPS
      service: name=org.cups.cupsd.service enabled=no state=stopped
