---
- name: redshift
  tags: ['redshift']
  block:
    - name: install redshift
      pacman: name=redshift state=present

    - name: stow dotfile config
      stow: package=redshift
      become_user: "{{ user.name }}"

    - name: enable redshift user service
      systemd:
        name: redshift.service
        enabled: True
        scope: user
        state: started
        become_user: "{{ user.name }}"
