---
- name: shell and terminal config
  tags: ['shell']
  become_user: "{{ user.name }}"
  block:

    - import_role: name=dotfiles tasks_from=register_dotfiles_util
      vars:
        dotfiles: ['zsh', 'tmux']

    - name: install packages
      import_role: name=pkgs tasks_from=util__install_packages
      vars:
        packages:
          - antibody
          - exa
          - fd
          - fzf
          - jq
          - jp
          - tmux
          - tmuxinator
          - yq
          - zsh

    - name: enable tmux user service
      service: name=tmux scope=user enabled=yes state=started
