- name: install fonts
  pacman: name={{ item }} state=present
  with_items:
    - ttf-hack
    - ttf-dejavu
    - ttf-ubraille
    # Fonts to use asian characters
    - ttf-freefont
    - ttf-arphic-uming
    - ttf-baekmuk
    - ttf-indic-otf
    # Emoji
    - noto-fonts
    - ttf-hannom  # Vietnamese
    # Math
    - font-mathematica
