---
- name: xdg configs
  tags: ['xdg']
  become_user: "{{ user.name }}"
  block:

    # via https://wiki.archlinux.org/index.php/XDG_MIME_Applications
    # TODO -> do with chezmoi
    - name: symlink mimeapps to deprecated location
      file:
        src: "$MY_DOTFILES/xdg/.config/mimeapps.list"
        dest: "$HOME/.local/share/applications/mimeapps.list"
        state: link
