---
- name: bootstrap dotfiles
  tags: ['dotfiles']
  block:
    - name: install stow to manage symlinks
      pacman: name=stow
      
    - name: clone dotfiles
      git:
        repo: "{{ dotfiles.repo }}"
        dest: "{{ dotfiles.directory }}"
        recursive: yes
        track_submodules: yes
      become_user: "{{ user.name }}"

    - name: install dotfiles dependencies
      pacman: name="{{ item }}" state=present
      with_items: "{{ dotfiles.deps }}"

    - name: install dotfiles
      stow: package="{{ item }}"
      with_items: "{{ dotfiles.generic_dotfiles }}"
      become_user: "{{ user.name }}"
