---
- name: bootstrap dotfiles
  tags: ['dotfiles']
  become_user: "{{ user.name }}"
  block:

    - name: clone dotfiles
      git:
        repo: "{{ dotfiles_vars.repo }}"
        dest: "$MY_DOTFILES"
        version: master
        recursive: yes
        track_submodules: yes
      register: warning
      failed_when: warning.failed and warning.msg != "Local modifications exist in repository (force=no)."
