---
- name: find original files
  stat:
    path: "/{{ item.path }}"
  with_filetree: "{{ source_dir }}/{{ package }}"
  when:
    - item.state == 'file'
  register: original_files
  no_log: True
- name: rm original files
  file:
    path: "{{ item.stat.path }}"
    state: absent
  with_items: "{{ original_files.results }}"
  when:
    - item.stat is defined
    - item.stat.exists
    - not item.stat.islnk
- name: Stow dotfiles
  stow:
    package: "{{ package }}"
    source_dir: "{{ source_dir }}"
    target_dir: "{{ target_dir }}"
